---
title: "Time Series Analysis - Micro Perspective"
output: html_notebook
---

```{r}
install.packages("ggplot2")
library(ggplot2)
library(reshape2)
options(scipen = 999)
```


```{r}
aggregated_data <- read.csv(file="../../parity_data/rgd_1523059200_to_1524528000.csv", header=TRUE, sep=",")
aggregated_data <- aggregated_data[3:16, ]

aggregated_data$day <- aggregated_data$day / 1000000000
aggregated_data$day <- as.POSIXct(aggregated_data$day, origin="1970-01-01")

aggregated_data$total_events <- 0
aggregated_data$total_events <- rowSums(aggregated_data[2:24])
```

# See the overall amount of events
First we want to analyze how many cases took place. Note that this bar plot includes the start and end events for every case.

```{r}
pdf("transition_amount_by_day_micro.pdf", width=12, height=6)
transition_day <- ggplot(aggregated_data, aes(x=day, y=total_events)) + ylab('amount of transitions') + theme(plot.title = element_text(hjust = 0.5)) + geom_bar(stat='identity')
print(transition_day)
dev.off()
transition_day
```

```{r}
summary(transition_day)
```


This is with absolute values

```{r}
aggregated_data.m <- melt(aggregated_data[, 1:24], id.vars = "day")
ggplot(aggregated_data.m, aes(x = day, y = value, fill=variable)) +
    geom_bar(stat='identity')
```
This is with relative values

```{r}
pdf("transition_stacked_by_day_micro.pdf", width=12, height=6)
aggregated_data_relative <- cbind(aggregated_data)
aggregated_data_relative[, 2:24] = aggregated_data[, 2:24] /  aggregated_data[, 'total_events']
aggregated_data_relative.m <- melt(aggregated_data_relative[, 1:24], id.vars = "day")
p <- ggplot(aggregated_data_relative.m, aes(x = day, y = value, fill=variable)) +
    geom_bar(stat='identity')
print(p)
dev.off()
p
```

```{r}
sink("transitions_summary.txt")
print(summary(aggregated_data_relative))
sink()
```
```{r}
cleaned_aggregated_data_relative <- subset(aggregated_data_relative, select = -c(CtU..UtC, CtU..UtU, UtC..UtU, UtU..CtC, UtU..CtU, UtU..UtC, UtU..UtU))
```

Correlation analysis

```{r}
cormat <- round(cor(cleaned_aggregated_data_relative[, 2:17], method = c("pearson")),2)
melted_cormat <- melt(cormat)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
install.packages("corrplot")

library(corrplot)
```


```{r}
M <- round(cor(cleaned_aggregated_data_relative[, 2:17], method = c("pearson")),2)
png(height=1200, width=1500, pointsize=15, file="corrgram_micro.png")
corrplot(M, method="color", type="lower", order="hclust", addCoef.col = "black", tl.col="black", tl.srt=45)
dev.off()
```

